"""Bridge Short Drama Agent plans into existing CINEOS production contracts."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from uuid import NAMESPACE_URL, UUID, uuid5

from cineos.assets import AssetRegistry
from cineos.assets import Character as CanonicalCharacter
from cineos.assets.storage import save as save_asset_registry
from cineos.compiler import FilmPackage
from cineos.compiler import compile as compile_film_package
from cineos.compiler import save as save_film_package
from cineos.core import Character, Environment, MovieProject, Scene, Shot, Timeline

from .models import DramaPlan


def _project_namespace(plan: DramaPlan) -> UUID:
    return uuid5(NAMESPACE_URL, f"cineos-short-drama:{plan.brief.premise.strip()}")


def _canonical_characters(plan: DramaPlan) -> tuple[AssetRegistry, list[UUID]]:
    registry = AssetRegistry()
    selected_ids: list[UUID] = []
    namespace = _project_namespace(plan)
    for profile in plan.characters:
        asset_id = uuid5(namespace, f"character:{profile.character_id}")
        registry.register(
            CanonicalCharacter(
                asset_id=asset_id,
                name=profile.name,
                description=f"{profile.role} generated by CINEOS Short Drama Agent",
                tags={"short-drama", profile.role},
                metadata={
                    "short_drama_profile": profile.to_dict(),
                    "cinedna": {
                        "status": "pending-approved-reference",
                        "display_name": profile.name,
                        "required_identity_fields": ["face", "body"],
                    },
                },
            )
        )
        selected_ids.append(asset_id)
    return registry, selected_ids


def plan_to_movie_project(
    plan: DramaPlan,
    *,
    title: str | None = None,
    author: str = "CINEOS Short Drama Agent",
) -> MovieProject:
    """Convert a drama plan into the renderer-independent core project model.

    Canonical character assets are created with deterministic UUIDs. CineDNA is
    intentionally not fabricated: each asset is marked pending until approved
    identity references plus explicit face/body metadata exist.
    """
    if not isinstance(plan, DramaPlan):
        raise TypeError("plan must be a DramaPlan")

    canonical_registry, canonical_ids = _canonical_characters(plan)
    core_characters = [
        Character(
            asset_id=profile.character_id,
            name=profile.name,
            description=profile.role,
            metadata=profile.to_dict(),
        )
        for profile in plan.characters
    ]

    shots_by_scene: dict[str, list[dict]] = defaultdict(list)
    for shot in plan.shots:
        shots_by_scene[shot["scene_id"]].append(shot)

    location_ids: dict[str, str] = {}
    locations: list[Environment] = []
    last_location_name = "primary story location"
    for scene in plan.screenplay["scenes"]:
        location_name = scene.get("location") or last_location_name
        if location_name == "previous location":
            location_name = last_location_name
        else:
            last_location_name = location_name
        if location_name not in location_ids:
            location_id = f"location-{len(location_ids) + 1:03d}"
            location_ids[location_name] = location_id
            locations.append(
                Environment(
                    asset_id=location_id,
                    name=location_name,
                    description="Short Drama Agent planned environment",
                )
            )

    timeline = Timeline()
    project_scenes: list[Scene] = []
    for scene_index, scene_data in enumerate(plan.screenplay["scenes"], start=1):
        scene_id = scene_data["scene_id"]
        planned_shots = shots_by_scene.get(scene_id, [])
        core_shots = [
            Shot(
                shot_id=shot["shot_id"],
                camera=shot.get("shot_size", "medium"),
                lens=shot.get("lens", "50mm"),
                movement=shot.get("camera_movement", "static"),
                lighting=shot.get(
                    "lighting_intent", "motivated naturalistic light"
                ),
                action=shot.get("purpose") or scene_data.get("purpose", ""),
                dialogue="",
                duration=float(shot["duration_seconds"]),
            )
            for shot in planned_shots
        ]
        raw_location = scene_data.get("location") or last_location_name
        if raw_location == "previous location":
            location_name = (
                locations[-1].name if locations else "primary story location"
            )
        else:
            location_name = raw_location
        scene = Scene(
            scene_id=scene_id,
            title=f"{scene_index:02d} {scene_data['beat'].title()}",
            description=scene_data.get("purpose", ""),
            shots=core_shots,
            location=location_ids[location_name],
            characters=[profile.character_id for profile in plan.characters],
            duration=sum(shot.duration for shot in core_shots),
        )
        project_scenes.append(scene)
        timeline.add_scene(scene_id)
        for shot in core_shots:
            timeline.add_shot(scene_id, shot.shot_id)

    return MovieProject(
        title=title or plan.brief.premise.strip(),
        author=author,
        characters=core_characters,
        locations=locations,
        scenes=project_scenes,
        timeline=timeline,
        asset_registry=canonical_registry,
        asset_ids=canonical_ids,
        cinedna_ids=[],
    )


def compile_drama_plan(plan: DramaPlan) -> tuple[MovieProject, FilmPackage]:
    """Compile a Short Drama Agent plan through the existing Film Compiler."""
    project = plan_to_movie_project(plan)
    return project, compile_film_package(project)


def write_production_artifacts(
    plan: DramaPlan,
    output_dir: str | Path,
) -> dict[str, Path]:
    """Write the plan, canonical assets and compiled Film Package."""
    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)
    project, package = compile_drama_plan(plan)

    drama_path = destination / "drama-package.json"
    drama_path.write_text(
        json.dumps(plan.to_dict(), ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    asset_path = save_asset_registry(
        project.asset_registry,
        destination / "assets.json",
    )
    film_path = destination / "film-package.json"
    save_film_package(package, film_path)
    return {
        "drama_package": drama_path,
        "asset_registry": asset_path,
        "film_package": film_path,
    }
