"""Story structure generated by NOVA."""

import hashlib
import json
from dataclasses import asdict, dataclass, field


@dataclass(slots=True)
class StoryPlan:
    logline: str
    synopsis: str
    act_structure: list[dict[str, str]]
    dramatic_objective: str
    central_conflict: str
    turning_points: list[str]
    climax: str
    resolution: str
    character_arcs: dict[str, str] = field(default_factory=dict)
    estimated_duration: float = 0.0
    locked_constraints: list[str] = field(default_factory=list)
    rationale: str = ""

    @property
    def content_hash(self) -> str:
        payload = asdict(self)
        return hashlib.sha256(
            json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
        ).hexdigest()
